server:
  port: 8083

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:

        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
          filters:
            - RewritePath=/api/employees/(?<segment>.*), /employees/${segment}

        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**
          filters:
            - RewritePath=/api/departments/(?<segment>.*), /departments/${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
